version: 2
jobs:
  build-and-release:
    docker:
      - image: circleci/golang:1.10.3-stretch
    steps:
      - checkout

      - run:
          name: "Publish Release"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            go get -d ./...

            GOOS=linux go build -o ~/artifacts/hello_linux hello/hello.go
            GOOS=darwin go build -o ~/artifacts/hello_darwin hello/hello.go
            GOOS=windows go build -o ~/artifacts/hello_windows hello/hello.go

            VERSION=$(~/artifacts/hello_linux -version)
            HTTPS_URL="https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/tag/${VERSION}"
            STATUS=$(curl -s -o /dev/null -w '%{http_code}' ${HTTPS_URL})
            if [ $STATUS -eq 200 ]; then
            	echo "Release Already Made"
            else
              go get github.com/tcnksm/ghr 
            	ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/artifacts/
            fi
      - store_artifacts:
          path: ~/artifacts

workflows:
  version: 2
  main: 
    jobs: 
      - build-and-release