workflows:
  version: 2
  jobs:
    - build:
        filters:
          tags:
            only: /^\d+\.\d+\.\d+$/
        steps:
          - checkout
          - run: GOOS=linux go build -o hello_linux hello/hello.go
          - run: GOOS=darwin go build -o hello_darwin hello/hello.go
          - run: GOOS=windows go build -o hello_windows hello/hello.go
      # - publish-github-release:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^\d+\.\d+\.\d+$/
      #     docker:
      #       - image: circleci/golang:1.10.3-stretch
      #     steps:
      #       - attach_workspace:
      #         at: ./artifacts
      #       - run:
      #         name: "Publish Release on GitHub"
      #         command: |
      #           go get github.com/tcnksm/ghr
      #           VERSION=$(my-binary --version)
      #           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
